#################
# local configs #
#################

   
server.port: 8010

spring.datasource:
   url: ...
   username: ...
   password: ...
   driver-class-name: ...
   
x-mattersCredentials:
   username: ...
   password: ...
   
x-mattersUrl:
   allocation: ...
   pickDecline: ...
   creationFailure: ...
   driftAnalysis: ...


metrics:
   allocation:
       name: 'Allocation Failure Percentage'
       threshold: ...
   pickDecline:
       name: 'Pick Decline Percentage'
       threshold: ...
   creationFailure:  
       name: 'DO Creation Failure Minutes Passed'
       threshold: ...
   driftAnalysis:
       name: 'Drift Analysis Data'
       
jasypt:
   encryptor:
       algorithm: PBEWithMD5AndDES
       password: ...
        


